swing_height: 0.12
push_down_height: 0.002
#push_down_height: 0.02
default_target_foot_location: [-0.08, -0.11, 0.0]

## Feedback Gain
# config x6
# Kp: [ 50, 50, 50, 50, 50, 50]
# Kd: [ 5, 5, 5, 5, 5, 5]

Kp: [ 150, 150, 150, 250, 250, 250]
Kd: [ 10, 10, 10, 10, 10, 10]

body_pt_offset: [0.0, 0.0]
#body_pt_offset: [0.005, 0.008]
foot_landing_offset: [0.0, 0.0]
swing_time_reduction: 0.0

